
import { MobilePhone, Brand } from './types';

export const BRANDS: Brand[] = [
  { name: 'Samsung', count: 145 },
  { name: 'Apple', count: 82 },
  { name: 'Xiaomi', count: 120 },
  { name: 'Vivo', count: 95 },
  { name: 'Oppo', count: 88 },
  { name: 'Realme', count: 76 },
  { name: 'Infinix', count: 64 },
  { name: 'Tecno', count: 58 },
  { name: 'Huawei', count: 42 },
  { name: 'OnePlus', count: 35 },
  { name: 'Google', count: 12 },
  { name: 'Motorola', count: 28 },
];

export const MOCK_MOBILES: MobilePhone[] = [
  {
    id: '1',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    price: 399999,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/s24u/400/500',
    specs: {
      processor: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      storage: '256GB/512GB/1TB',
      display: '6.8" Dynamic LTPO AMOLED 2X',
      camera: '200MP Quad Camera',
      battery: '5000mAh',
      os: 'Android 14, One UI 6.1',
    },
    releaseDate: 'Jan 2024',
    rating: 4.8,
    isTrending: true,
  },
  {
    id: '2',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    price: 450000,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/ip15pm/400/500',
    specs: {
      processor: 'A17 Pro',
      ram: '8GB',
      storage: '256GB/512GB/1TB',
      display: '6.7" LTPO Super Retina XDR OLED',
      camera: '48MP Triple Camera',
      battery: '4441mAh',
      os: 'iOS 17',
    },
    releaseDate: 'Sept 2023',
    rating: 4.9,
    isTrending: true,
  },
  {
    id: '3',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price: 285000,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/x14u/400/500',
    specs: {
      processor: 'Snapdragon 8 Gen 3',
      ram: '16GB',
      storage: '512GB',
      display: '6.73" LTPO AMOLED',
      camera: '50MP Quad Leica Camera',
      battery: '5000mAh',
      os: 'Android 14, HyperOS',
    },
    releaseDate: 'Feb 2024',
    rating: 4.7,
    isTrending: false,
  },
  {
    id: '4',
    name: 'Vivo V30 Pro',
    brand: 'Vivo',
    price: 159999,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/vv30/400/500',
    specs: {
      processor: 'Dimensity 8200',
      ram: '12GB',
      storage: '512GB',
      display: '6.78" AMOLED',
      camera: '50MP Triple Zeiss Camera',
      battery: '5000mAh',
      os: 'Android 14, Funtouch 14',
    },
    releaseDate: 'Mar 2024',
    rating: 4.5,
    isTrending: true,
  },
  {
    id: '5',
    name: 'Infinix Note 40 Pro',
    brand: 'Infinix',
    price: 69999,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/in40/400/500',
    specs: {
      processor: 'Helio G99 Ultimate',
      ram: '8GB',
      storage: '256GB',
      display: '6.78" AMOLED',
      camera: '108MP Triple Camera',
      battery: '5000mAh',
      os: 'Android 14, XOS 14',
    },
    releaseDate: 'Mar 2024',
    rating: 4.2,
    isTrending: true,
  },
  {
    id: '6',
    name: 'Realme GT 5',
    brand: 'Realme',
    price: 124999,
    currency: 'Rs.',
    image: 'https://picsum.photos/seed/rgt5/400/500',
    specs: {
      processor: 'Snapdragon 8 Gen 2',
      ram: '12GB/16GB',
      storage: '256GB/512GB',
      display: '6.74" AMOLED',
      camera: '50MP Triple Camera',
      battery: '5240mAh',
      os: 'Android 13, Realme UI 4.0',
    },
    releaseDate: 'Aug 2023',
    rating: 4.4,
    isTrending: false,
  },
];
